apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: caj-fare-alert
spec:
  groups:
    - name: caj-fare
      rules:
        - alert: CpuUsageAlert
          annotations:
            summary: >-
              {{ $labels.app }} in {{ $labels.namespace }} cpu is greater than
              1%
          expr: >-
            process_cpu_usage{app="caj-fare",namespace="caj-fare"} >
            0.01
          for: 5s
          labels:
            severity: Critical