apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: caj-fare-alert
spec:
  groups:
    - name: caj-fare
      rules:
        - alert: API Request
          annotations:
            summary: >-
              {{ $labels.app }} in {{ $labels.namespace }} API Request is greater than
              1
          expr: >-
            http_server_requests_seconds_count{namespace='user1', app='caj-fare', uri='/api/hostname'} > 1
          for: 5s
          labels:
            severity: Critical
