apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: caj-fare
spec:
  endpoints:
    - interval: 10s
      path: /actuator/prometheus
      port: http
      scheme: http
  selector:
    matchLabels:
      app: caj-fare
  targetLabels:
    - app